### ISSUE TITLE
Can't compile project make: Nothing to be done for 'all'.

### ISSUE THREAD

**Issue by alexyorke** [Tunous/Waller#3]
Here's the error I'm getting:

> decagon@ubuntu ~/Waller % ls
> art	      Makefile	     README.md	  stylesheet.css  wall.js
> extension.js  metadata.json  schemas	  timer.js
> LICENSE       prefs.js	     Settings.ui  utils.js
> decagon@ubuntu ~/Waller % make
> make: Nothing to be done for 'all'.

I'm on Ubuntu 16.04 with all updates installed as of November 5th. I cloned the project from the master branch just now.

**Comment by Tunous** [comment]
That's not an error. It just indicates that everything is compiled and no changes are required. `make` command alone only compiles the schemas files. To actually build/install you can run `make build` or `make install`.
